# Generated by Django 4.0.2 on 2022-03-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_alter_patient_options_remove_patient_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='serviceitem',
            field=models.ManyToManyField(to='cabinet.ServiceItem'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N-B', 'Non-binary')], default='F', max_length=3),
        ),
    ]
