# Generated by Django 4.0.2 on 2022-03-02 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_remove_serviceitem_invoice_invoice_serviceitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='serviceitem',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='title',
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.invoice'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.service'),
        ),
    ]
